spring.application.name=cfl_project
spring.datasource.url=jdbc:postgresql://localhost:5432/cfl-new1
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=9048

server.port=9040


Secret_String="a8fd8244d2ce5169518d8980cb0cac27d2d82479cfa7e0263d1d382828790c3ebd7e9274c92b153e88e222ab262f1603d787dfbec4a29c03befb2487eb7c7c23";


spring.mail.host=mapi.cms.co.in
spring.mail.port=587
spring.mail.username=startsmart@cms.co.in
spring.mail.password=Dell@2020

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=50000


logging.level.org.springframework.mail=DEBUG

spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=*

#server.tomcat.relaxed-query-chars=|,{,},[,]

# Maximum file size (example: 20MB)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

